#!/bin/bash
# Script to restart the Discord bot deployment to pull the latest image

echo "Restarting Discord bot deployment to pull latest image..."
echo ""
echo "Run these commands on the Kubernetes cluster (192.168.100.60):"
echo ""
echo "# Option 1: Force pull new image by restarting deployment"
echo "kubectl -n discord-bots rollout restart deployment discord-casual"
echo ""
echo "# Option 2: Delete pod to force recreation with new image"
echo "kubectl -n discord-bots delete pod -l app=discord-casual"
echo ""
echo "# Check status"
echo "kubectl -n discord-bots get pods -w"
echo ""
echo "# View logs to confirm /imagine command is registered"
echo "kubectl -n discord-bots logs -l app=discord-casual | grep -E 'imagine|command'"
echo ""
echo "The new image with enhanced /imagine command has been built and pushed to:"
echo "ghcr.io/sudoflux/discord-casual:latest"
echo ""
echo "After restarting, the bot should:"
echo "1. Clear existing commands"
echo "2. Register all commands including enhanced /imagine with:"
echo "   - Required: prompt"
echo "   - Optional: negative prompt, width, height, seed"
echo "3. Sync commands globally and to the guild"
echo "4. Log confirmation that /imagine is registered"
echo ""
echo "New features in /imagine:"
echo "- Quality presets for better images:"
echo "    • fast: 4 steps, 0.0 guidance (original speed)"
echo "    • balanced: 8 steps, 2.0 guidance (recommended)"
echo "    • quality: 12 steps, 3.5 guidance (best quality)"
echo "    • high: 20 steps, 5.0 guidance (hidden option)"
echo "- Negative prompts to avoid unwanted elements"
echo "- Custom dimensions (512-1024 pixels)"
echo "- Seed for reproducible results"
echo "- Better validation and user feedback"
echo ""
echo "Example usage:"
echo "/imagine prompt: cyberpunk city quality: quality"
echo "/imagine prompt: portrait quality: balanced negative: blurry"