name: Build and Publish

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'      # e.g., v0.1.0

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-buildx-action@v3
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/sudoflux/discord-casual
          tags: |
            type=ref,event=branch,enable=${{ startsWith(github.ref, 'refs/heads/main') }},value=latest
            type=semver,pattern={{version}}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}